.TH "SOGLVA/src/API.cpp" 3 "Tue Apr 27 2021" "Version 0.01" "SOGLVA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SOGLVA/src/API.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'API\&.h'\fP
.br
\fC#include <nuklear\&.h>\fP
.br
\fC#include <glfw_opengl3/nuklear_glfw_gl3\&.h>\fP
.br
\fC#include <stb_image\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNK_INCLUDE_FIXED_TYPES\fP"
.br
.ti -1c
.RI "#define \fBNK_INCLUDE_STANDARD_IO\fP"
.br
.ti -1c
.RI "#define \fBNK_INCLUDE_STANDARD_VARARGS\fP"
.br
.ti -1c
.RI "#define \fBNK_INCLUDE_DEFAULT_ALLOCATOR\fP"
.br
.ti -1c
.RI "#define \fBNK_INCLUDE_VERTEX_BUFFER_OUTPUT\fP"
.br
.ti -1c
.RI "#define \fBNK_INCLUDE_FONT_BAKING\fP"
.br
.ti -1c
.RI "#define \fBNK_INCLUDE_DEFAULT_FONT\fP"
.br
.ti -1c
.RI "#define \fBNK_KEYSTATE_BASED_INPUT\fP"
.br
.ti -1c
.RI "#define \fBNK_IMPLEMENTATION\fP"
.br
.ti -1c
.RI "#define \fBNK_GLFW_GL3_IMPLEMENTATION\fP"
.br
.ti -1c
.RI "#define \fBSTB_IMAGE_IMPLEMENTATION\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "HWND \fBSOGLVAInitialize\fP ()"
.br
.ti -1c
.RI "void \fBSOGLVARunApp\fP ()"
.br
.ti -1c
.RI "void \fBSOGLVARestart\fP ()"
.br
.ti -1c
.RI "void \fBSOGLVADestroy\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define NK_GLFW_GL3_IMPLEMENTATION"

.PP
Definition at line 12 of file API\&.cpp\&.
.SS "#define NK_IMPLEMENTATION"

.PP
Definition at line 11 of file API\&.cpp\&.
.SS "#define NK_INCLUDE_DEFAULT_ALLOCATOR"

.PP
Definition at line 6 of file API\&.cpp\&.
.SS "#define NK_INCLUDE_DEFAULT_FONT"

.PP
Definition at line 9 of file API\&.cpp\&.
.SS "#define NK_INCLUDE_FIXED_TYPES"

.PP
Definition at line 3 of file API\&.cpp\&.
.SS "#define NK_INCLUDE_FONT_BAKING"

.PP
Definition at line 8 of file API\&.cpp\&.
.SS "#define NK_INCLUDE_STANDARD_IO"

.PP
Definition at line 4 of file API\&.cpp\&.
.SS "#define NK_INCLUDE_STANDARD_VARARGS"

.PP
Definition at line 5 of file API\&.cpp\&.
.SS "#define NK_INCLUDE_VERTEX_BUFFER_OUTPUT"

.PP
Definition at line 7 of file API\&.cpp\&.
.SS "#define NK_KEYSTATE_BASED_INPUT"

.PP
Definition at line 10 of file API\&.cpp\&.
.SS "#define STB_IMAGE_IMPLEMENTATION"

.PP
Definition at line 16 of file API\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "void SOGLVADestroy ()"

.PP
Definition at line 46 of file API\&.cpp\&.
.SS "HWND SOGLVAInitialize ()"

.PP
Definition at line 28 of file API\&.cpp\&.
.SS "void SOGLVARestart ()"
not implemented
.PP
Definition at line 40 of file API\&.cpp\&.
.SS "void SOGLVARunApp ()"

.PP
Definition at line 34 of file API\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SOGLVA from the source code\&.
