.TH "SOGLVA/src/Core/UI/Panels Directory Reference" 3 "Tue Apr 27 2021" "Version 0.01" "SOGLVA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SOGLVA/src/Core/UI/Panels Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBasePanel\&.h\fP"
.br
.ti -1c
.RI "file \fBFPSCounter\&.cpp\fP"
.br
.ti -1c
.RI "file \fBFPSCounter\&.h\fP"
.br
.ti -1c
.RI "file \fBProperty\&.cpp\fP"
.br
.ti -1c
.RI "file \fBProperty\&.h\fP"
.br
.in -1c
