.TH "SOGLVA/src/InputHandler Directory Reference" 3 "Tue Apr 27 2021" "Version 0.01" "SOGLVA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SOGLVA/src/InputHandler Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBDefaultInput\&.cpp\fP"
.br
.ti -1c
.RI "file \fBDefaultInput\&.h\fP"
.br
.in -1c
