.TH "SOGLVA/src/InputHandler/DefaultInput.cpp" 3 "Tue Apr 27 2021" "Version 0.01" "SOGLVA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SOGLVA/src/InputHandler/DefaultInput.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'DefaultInput\&.h'\fP
.br
\fC#include 'API\&.h'\fP
.br
\fC#include 'ManagedObject/Components/Camera\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBSOGLVA\fP"
.br
.ti -1c
.RI " \fBSOGLVA::INPUTHANDLER\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBSOGLVA::INPUTHANDLER::DefaultKeyboardInput\fP (\fBSOGLVA::CORE::RENDERING::Rendering\fP &rendering)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SOGLVA from the source code\&.
