.TH "ManagedObject" 3 "Tue Apr 27 2021" "Version 0.01" "SOGLVA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ManagedObject
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ManagedObject\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.ti -1c
.RI "\fBManagedObject\fP (std::string \fBname\fP='Default Object')"
.br
.ti -1c
.RI "\fB~ManagedObject\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBname\fP"
.br
.ti -1c
.RI "std::set< \fBIComponent\fP * > \fBcomponents\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file ManagedObject\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ManagedObject::ManagedObject (std::string name = \fC'Default Object'\fP)\fC [inline]\fP"

.PP
Definition at line 27 of file ManagedObject\&.h\&.
.SS "ManagedObject::~ManagedObject ()\fC [inline]\fP"

.PP
Definition at line 31 of file ManagedObject\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void ManagedObject::Update ()\fC [inline]\fP"

.PP
Definition at line 19 of file ManagedObject\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "std::set<\fBIComponent\fP*> ManagedObject::components"

.PP
Definition at line 17 of file ManagedObject\&.h\&.
.SS "std::string ManagedObject::name"

.PP
Definition at line 16 of file ManagedObject\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SOGLVA from the source code\&.
