.TH "SOGLVA/src/ManagedObject/ManagedObject.h" 3 "Tue Apr 27 2021" "Version 0.01" "SOGLVA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SOGLVA/src/ManagedObject/ManagedObject.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Components/IComponent\&.h'\fP
.br
\fC#include 'Components/Camera\&.h'\fP
.br
\fC#include 'Components/Transform\&.h'\fP
.br
\fC#include 'Components/Graphics/Mesh\&.h'\fP
.br
\fC#include 'Components/Graphics/Model\&.h'\fP
.br
\fC#include 'Components/Graphics/Shader\&.h'\fP
.br
\fC#include 'Components/Physic\&.h'\fP
.br
\fC#include <set>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSOGLVA::MANAGED_OBJECT::ManagedObject\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBSOGLVA\fP"
.br
.ti -1c
.RI " \fBSOGLVA::MANAGED_OBJECT\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SOGLVA from the source code\&.
