.TH "md__s_o_g_l_v_a__readme" 3 "Tue Apr 27 2021" "Version 0.01" "SOGLVA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__s_o_g_l_v_a__readme \- Readme 
common: \fBnuklearImport\&.h\fP : simplify nuklear import standard\&.h : define standard library
.PP
components: Graphics:
.IP "\(bu" 2
Camera Transform
.PP
.PP
EventHandler: event
.PP
workflow: 
.PP
.nf
SOGLVA  - RenderingSystem: ISystem
        - UISystem       : ISystem
        - SceneSystem    : ISystem

.fi
.PP
 
