.TH "SOGLVA/src/ManagedObject/Components/Graphics/Model.h" 3 "Tue Apr 27 2021" "Version 0.01" "SOGLVA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SOGLVA/src/ManagedObject/Components/Graphics/Model.h
.SH SYNOPSIS
.br
.PP
\fC#include <assimp/Importer\&.hpp>\fP
.br
\fC#include <assimp/scene\&.h>\fP
.br
\fC#include <assimp/postprocess\&.h>\fP
.br
\fC#include 'Mesh\&.h'\fP
.br
\fC#include '\&.\&./IComponent\&.h'\fP
.br
\fC#include '\&.\&./Transform\&.h'\fP
.br
\fC#include '\&.\&./Camera\&.h'\fP
.br
\fC#include <vector>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSOGLVA::MANAGED_OBJECT::COMPONENT::Model\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBSOGLVA\fP"
.br
.ti -1c
.RI " \fBSOGLVA::MANAGED_OBJECT\fP"
.br
.ti -1c
.RI " \fBSOGLVA::MANAGED_OBJECT::COMPONENT\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SOGLVA from the source code\&.
