.TH "SOGLVA/src/common/NuklearImport.h" 3 "Tue Apr 27 2021" "Version 0.01" "SOGLVA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SOGLVA/src/common/NuklearImport.h
.SH SYNOPSIS
.br
.PP
\fC#include <nuklear\&.h>\fP
.br
\fC#include <glfw_opengl3/nuklear_glfw_gl3\&.h>\fP
.br
\fC#include <style\&.c>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNK_INCLUDE_FIXED_TYPES\fP"
.br
.ti -1c
.RI "#define \fBNK_INCLUDE_STANDARD_IO\fP"
.br
.ti -1c
.RI "#define \fBNK_INCLUDE_STANDARD_VARARGS\fP"
.br
.ti -1c
.RI "#define \fBNK_INCLUDE_DEFAULT_ALLOCATOR\fP"
.br
.ti -1c
.RI "#define \fBNK_INCLUDE_VERTEX_BUFFER_OUTPUT\fP"
.br
.ti -1c
.RI "#define \fBNK_INCLUDE_FONT_BAKING\fP"
.br
.ti -1c
.RI "#define \fBNK_INCLUDE_DEFAULT_FONT\fP"
.br
.ti -1c
.RI "#define \fBNK_KEYSTATE_BASED_INPUT\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define NK_INCLUDE_DEFAULT_ALLOCATOR"

.PP
Definition at line 5 of file NuklearImport\&.h\&.
.SS "#define NK_INCLUDE_DEFAULT_FONT"

.PP
Definition at line 8 of file NuklearImport\&.h\&.
.SS "#define NK_INCLUDE_FIXED_TYPES"

.PP
Definition at line 2 of file NuklearImport\&.h\&.
.SS "#define NK_INCLUDE_FONT_BAKING"

.PP
Definition at line 7 of file NuklearImport\&.h\&.
.SS "#define NK_INCLUDE_STANDARD_IO"

.PP
Definition at line 3 of file NuklearImport\&.h\&.
.SS "#define NK_INCLUDE_STANDARD_VARARGS"

.PP
Definition at line 4 of file NuklearImport\&.h\&.
.SS "#define NK_INCLUDE_VERTEX_BUFFER_OUTPUT"

.PP
Definition at line 6 of file NuklearImport\&.h\&.
.SS "#define NK_KEYSTATE_BASED_INPUT"

.PP
Definition at line 9 of file NuklearImport\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SOGLVA from the source code\&.
