.TH "SOGLVA/src/Core/Rendering/RenderingDef.h" 3 "Tue Apr 27 2021" "Version 0.01" "SOGLVA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SOGLVA/src/Core/Rendering/RenderingDef.h
.SH SYNOPSIS
.br
.PP
\fC#include <GL/glew\&.h>\fP
.br
\fC#include <GLFW/glfw3\&.h>\fP
.br
\fC#include <GLFW/glfw3native\&.h>\fP
.br
\fC#include <Windows\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGLFW_EXPOSE_NATIVE_WIN32\fP"
.br
.ti -1c
.RI "#define \fBNOMINMAX\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define GLFW_EXPOSE_NATIVE_WIN32"
Definition header for rendering system eg\&. glew, glfw \&.\&.\&.\&. 
.PP
Definition at line 9 of file RenderingDef\&.h\&.
.SS "#define NOMINMAX"

.PP
Definition at line 12 of file RenderingDef\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SOGLVA from the source code\&.
