.TH "SOGLVA/src/ManagedObject/Components/Graphics/Shader.h" 3 "Tue Apr 27 2021" "Version 0.01" "SOGLVA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SOGLVA/src/ManagedObject/Components/Graphics/Shader.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Core/Rendering/RenderingDef\&.h'\fP
.br
\fC#include <glm/glm\&.hpp>\fP
.br
\fC#include <glm/gtc/type_ptr\&.hpp>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSOGLVA::MANAGED_OBJECT::COMPONENT::Shader\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBSOGLVA\fP"
.br
.ti -1c
.RI " \fBSOGLVA::MANAGED_OBJECT\fP"
.br
.ti -1c
.RI " \fBSOGLVA::MANAGED_OBJECT::COMPONENT\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SOGLVA from the source code\&.
