.TH "SOGLVA::MANAGED_OBJECT::COMPONENT::Vertex" 3 "Tue Apr 27 2021" "Version 0.01" "SOGLVA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SOGLVA::MANAGED_OBJECT::COMPONENT::Vertex
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Mesh\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "glm::vec3 \fBPosition\fP"
.br
.ti -1c
.RI "glm::vec3 \fBNormal\fP"
.br
.ti -1c
.RI "glm::vec2 \fBTexCoords\fP"
.br
.ti -1c
.RI "glm::vec3 \fBTangent\fP"
.br
.ti -1c
.RI "glm::vec3 \fBBitangent\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file Mesh\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "glm::vec3 SOGLVA::MANAGED_OBJECT::COMPONENT::Vertex::Bitangent"

.PP
Definition at line 36 of file Mesh\&.h\&.
.SS "glm::vec3 SOGLVA::MANAGED_OBJECT::COMPONENT::Vertex::Normal"

.PP
Definition at line 30 of file Mesh\&.h\&.
.SS "glm::vec3 SOGLVA::MANAGED_OBJECT::COMPONENT::Vertex::Position"

.PP
Definition at line 28 of file Mesh\&.h\&.
.SS "glm::vec3 SOGLVA::MANAGED_OBJECT::COMPONENT::Vertex::Tangent"

.PP
Definition at line 34 of file Mesh\&.h\&.
.SS "glm::vec2 SOGLVA::MANAGED_OBJECT::COMPONENT::Vertex::TexCoords"

.PP
Definition at line 32 of file Mesh\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SOGLVA from the source code\&.
