.TH "SOGLVA/src/SOGLVA.cpp" 3 "Tue Apr 27 2021" "Version 0.01" "SOGLVA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SOGLVA/src/SOGLVA.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'SOGLVA\&.h'\fP
.br
\fC#include 'InputHandler/DefaultInput\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBSOGLVA\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SOGLVA from the source code\&.
