.TH "SOGLVA::MANAGED_OBJECT::COMPONENT" 3 "Tue Apr 27 2021" "Version 0.01" "SOGLVA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SOGLVA::MANAGED_OBJECT::COMPONENT
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCamera\fP"
.br
.ti -1c
.RI "struct \fBTexture\fP"
.br
.ti -1c
.RI "struct \fBVertex\fP"
.br
.ti -1c
.RI "class \fBMesh\fP"
.br
.ti -1c
.RI "class \fBModel\fP"
.br
.ti -1c
.RI "class \fBShader\fP"
.br
.ti -1c
.RI "class \fBIComponent\fP"
.br
.ti -1c
.RI "class \fBLighting\fP"
.br
.ti -1c
.RI "class \fBPhysic\fP"
.br
.ti -1c
.RI "class \fBTransform\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "unsigned int \fBTextureFromFile\fP (const char *path, const std::string &directory, bool gamma)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "unsigned int SOGLVA::MANAGED_OBJECT::COMPONENT::TextureFromFile (const char * path, const std::string & directory, bool gamma)"

.PP
Definition at line 92 of file Mesh\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SOGLVA from the source code\&.
