.TH "SOGLVA/src/SOGLVA.h" 3 "Tue Apr 27 2021" "Version 0.01" "SOGLVA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SOGLVA/src/SOGLVA.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Core/Rendering/Rendering\&.h'\fP
.br
\fC#include 'Core/UI/UISystem\&.h'\fP
.br
\fC#include 'Core/Scene/SceneManager\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSOGLVA::Soglva\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBSOGLVA\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SOGLVA from the source code\&.
