.TH "SOGLVA::MANAGED_OBJECT" 3 "Tue Apr 27 2021" "Version 0.01" "SOGLVA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SOGLVA::MANAGED_OBJECT
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBCOMPONENT\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBManagedObject\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SOGLVA from the source code\&.
