.TH "SOGLVA::CORE::UI" 3 "Tue Apr 27 2021" "Version 0.01" "SOGLVA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SOGLVA::CORE::UI
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBPANEL\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIUIDrawable\fP"
.br
.ti -1c
.RI "class \fBUISystem\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SOGLVA from the source code\&.
