.TH "SOGLVA::CORE::UI::PANEL::BasePanel" 3 "Tue Apr 27 2021" "Version 0.01" "SOGLVA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SOGLVA::CORE::UI::PANEL::BasePanel \- abstract for every nuklear panel  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BasePanel\&.h>\fP
.PP
Inherited by \fBSOGLVA::CORE::UI::PANEL::FPSCounter\fP, and \fBSOGLVA::CORE::UI::PANEL::Property\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBasePanel\fP (nk_context *&_context, \fBSOGLVA::CORE::RENDERING::Rendering\fP &_rendering, const std::string &_name)"
.br
.ti -1c
.RI "\fB~BasePanel\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "nk_context *& \fBcontext\fP"
.br
.ti -1c
.RI "\fBSOGLVA::CORE::RENDERING::Rendering\fP & \fBrendering\fP"
.br
.ti -1c
.RI "std::string \fBname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
abstract for every nuklear panel 


.PP
Definition at line 11 of file BasePanel\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SOGLVA::CORE::UI::PANEL::BasePanel::BasePanel (nk_context *& _context, \fBSOGLVA::CORE::RENDERING::Rendering\fP & _rendering, const std::string & _name)\fC [inline]\fP"

.PP
Definition at line 19 of file BasePanel\&.h\&.
.SS "SOGLVA::CORE::UI::PANEL::BasePanel::~BasePanel ()\fC [inline]\fP"

.PP
Definition at line 22 of file BasePanel\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "nk_context*& SOGLVA::CORE::UI::PANEL::BasePanel::context\fC [protected]\fP"

.PP
Definition at line 14 of file BasePanel\&.h\&.
.SS "std::string SOGLVA::CORE::UI::PANEL::BasePanel::name\fC [protected]\fP"

.PP
Definition at line 16 of file BasePanel\&.h\&.
.SS "\fBSOGLVA::CORE::RENDERING::Rendering\fP& SOGLVA::CORE::UI::PANEL::BasePanel::rendering\fC [protected]\fP"

.PP
Definition at line 15 of file BasePanel\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SOGLVA from the source code\&.
