.TH "SOGLVA::INPUTHANDLER" 3 "Tue Apr 27 2021" "Version 0.01" "SOGLVA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SOGLVA::INPUTHANDLER
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBDefaultKeyboardInput\fP (\fBSOGLVA::CORE::RENDERING::Rendering\fP &rendering)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void SOGLVA::INPUTHANDLER::DefaultKeyboardInput (\fBSOGLVA::CORE::RENDERING::Rendering\fP & rendering)"

.PP
Definition at line 9 of file DefaultInput\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SOGLVA from the source code\&.
