.TH "SOGLVA::CORE::UI::PANEL::FPSCounter" 3 "Tue Apr 27 2021" "Version 0.01" "SOGLVA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SOGLVA::CORE::UI::PANEL::FPSCounter
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FPSCounter\&.h>\fP
.PP
Inherits \fBSOGLVA::CORE::UI::IUIDrawable\fP, and \fBSOGLVA::CORE::UI::PANEL::BasePanel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFPSCounter\fP (nk_context *&_context, \fBSOGLVA::CORE::RENDERING::Rendering\fP &_rendering, const std::string &_name)"
.br
.ti -1c
.RI "virtual void \fBDraw\fP () override"
.br
.RI "Draw Panel "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::string \fBfpsText\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 8 of file FPSCounter\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SOGLVA::CORE::UI::PANEL::FPSCounter::FPSCounter (nk_context *& _context, \fBSOGLVA::CORE::RENDERING::Rendering\fP & _rendering, const std::string & _name)\fC [inline]\fP"

.PP
Definition at line 14 of file FPSCounter\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void SOGLVA::CORE::UI::PANEL::FPSCounter::Draw ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Draw Panel 
.PP
Implements \fBSOGLVA::CORE::UI::IUIDrawable\fP\&.
.PP
Definition at line 7 of file FPSCounter\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string SOGLVA::CORE::UI::PANEL::FPSCounter::fpsText\fC [private]\fP"

.PP
Definition at line 11 of file FPSCounter\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SOGLVA from the source code\&.
