.TH "SOGLVA::MANAGED_OBJECT::COMPONENT::IComponent" 3 "Tue Apr 27 2021" "Version 0.01" "SOGLVA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SOGLVA::MANAGED_OBJECT::COMPONENT::IComponent
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <IComponent\&.h>\fP
.PP
Inherited by \fBSOGLVA::MANAGED_OBJECT::COMPONENT::Camera\fP, \fBSOGLVA::MANAGED_OBJECT::COMPONENT::Lighting\fP, and \fBSOGLVA::MANAGED_OBJECT::COMPONENT::Model\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBStart\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBUpdate\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBExit\fP ()=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file IComponent\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void SOGLVA::MANAGED_OBJECT::COMPONENT::IComponent::Exit ()\fC [pure virtual]\fP"

.PP
Implemented in \fBSOGLVA::MANAGED_OBJECT::COMPONENT::Lighting\fP, \fBSOGLVA::MANAGED_OBJECT::COMPONENT::Model\fP, and \fBSOGLVA::MANAGED_OBJECT::COMPONENT::Camera\fP\&.
.SS "virtual void SOGLVA::MANAGED_OBJECT::COMPONENT::IComponent::Start ()\fC [pure virtual]\fP"

.PP
Implemented in \fBSOGLVA::MANAGED_OBJECT::COMPONENT::Lighting\fP, \fBSOGLVA::MANAGED_OBJECT::COMPONENT::Model\fP, and \fBSOGLVA::MANAGED_OBJECT::COMPONENT::Camera\fP\&.
.SS "virtual void SOGLVA::MANAGED_OBJECT::COMPONENT::IComponent::Update ()\fC [pure virtual]\fP"

.PP
Implemented in \fBSOGLVA::MANAGED_OBJECT::COMPONENT::Lighting\fP, \fBSOGLVA::MANAGED_OBJECT::COMPONENT::Model\fP, and \fBSOGLVA::MANAGED_OBJECT::COMPONENT::Camera\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SOGLVA from the source code\&.
