.TH "SOGLVA::CORE" 3 "Tue Apr 27 2021" "Version 0.01" "SOGLVA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SOGLVA::CORE
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBRENDERING\fP"
.br
.ti -1c
.RI " \fBSCENE\fP"
.br
.ti -1c
.RI " \fBUI\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SOGLVA from the source code\&.
