.TH "SOGLVA/src/common/standard.h" 3 "Tue Apr 27 2021" "Version 0.01" "SOGLVA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SOGLVA/src/common/standard.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <string>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <set>\fP
.br
\fC#include <stdexcept>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for SOGLVA from the source code\&.
