.TH "Texture" 3 "Tue Apr 27 2021" "Version 0.01" "SOGLVA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Texture
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Mesh\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBid\fP"
.br
.ti -1c
.RI "std::string \fBtype\fP"
.br
.ti -1c
.RI "std::string \fBpath\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file Mesh\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned int Texture::id"

.PP
Definition at line 17 of file Mesh\&.h\&.
.SS "std::string Texture::path"

.PP
Definition at line 19 of file Mesh\&.h\&.
.SS "std::string Texture::type"

.PP
Definition at line 18 of file Mesh\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SOGLVA from the source code\&.
