.TH "UI::Panel::FPSCounter" 3 "Tue Apr 27 2021" "Version 0.01" "SOGLVA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UI::Panel::FPSCounter
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FPSCounter\&.h>\fP
.PP
Inherits \fBIUIDrawable\fP, and \fBBasePanel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFPSCounter\fP (nk_context *&_context, \fBRendering\fP &_rendering, const std::string &_name)"
.br
.ti -1c
.RI "virtual void \fBDraw\fP () override"
.br
.RI "Draw \fBPanel\fP "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 11 of file FPSCounter\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UI::Panel::FPSCounter::FPSCounter (nk_context *& _context, \fBRendering\fP & _rendering, const std::string & _name)\fC [inline]\fP"

.PP
Definition at line 17 of file FPSCounter\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void UI::Panel::FPSCounter::Draw ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Draw \fBPanel\fP 
.PP
Implements \fBIUIDrawable\fP\&.
.PP
Definition at line 7 of file FPSCounter\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SOGLVA from the source code\&.
