.TH "UI::Panel" 3 "Tue Apr 27 2021" "Version 0.01" "SOGLVA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UI::Panel
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFPSCounter\fP"
.br
.ti -1c
.RI "class \fBProperty\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SOGLVA from the source code\&.
