.TH "UISystem" 3 "Tue Apr 27 2021" "Version 0.01" "SOGLVA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UISystem \- this uiSystem class is for ui inside the opengl context\&. ui system use nuklear library for rendering ui inside the opengl context\&. this uisystem mean to be used in app for example for debugging or inapp ui not inside level editor\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <UISystem\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUISystem\fP (\fBRendering\fP &_rendering)"
.br
.ti -1c
.RI "\fB~UISystem\fP ()"
.br
.ti -1c
.RI "void \fBDrawUiPanels\fP ()"
.br
.RI "create nuklear_glfw frame and draw every panels inside vUIPanels "
.in -1c
.SH "Detailed Description"
.PP 
this uiSystem class is for ui inside the opengl context\&. ui system use nuklear library for rendering ui inside the opengl context\&. this uisystem mean to be used in app for example for debugging or inapp ui not inside level editor\&. 


.PP
Definition at line 17 of file UISystem\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UISystem::UISystem (\fBRendering\fP & _rendering)"

.PP
Definition at line 3 of file UISystem\&.cpp\&.
.SS "UISystem::~UISystem ()"

.PP
Definition at line 19 of file UISystem\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void UISystem::DrawUiPanels ()"

.PP
create nuklear_glfw frame and draw every panels inside vUIPanels 
.PP
Definition at line 29 of file UISystem\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SOGLVA from the source code\&.
