.TH "SOGLVA/src/Core/UI/UISystem.cpp" 3 "Tue Apr 27 2021" "Version 0.01" "SOGLVA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SOGLVA/src/Core/UI/UISystem.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'UISystem\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBSOGLVA\fP"
.br
.ti -1c
.RI " \fBSOGLVA::CORE\fP"
.br
.ti -1c
.RI " \fBSOGLVA::CORE::UI\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SOGLVA from the source code\&.
